### PR TITLE
Fix example in readme.

### PR DESCRIPTION
**Pull request by svetlyak40wt**
Seems package and basic action class were renamed.

### CODE REVIEW

**Comment by Shinmera** [comment]
The idea is that you use your own package local nickname for the example. There was no renaming.

**Comment by svetlyak40wt** [comment]
Basic-action was renamed to just Basic.

вс, 1 янв. 2023 г., 00:05 Nicolas Hafner ***@***.***>:

**Comment by Shinmera** [comment]
The current readme already has it as just `basic`.

**Comment by svetlyak40wt** [comment]
I understand that local nicknames can be used, but readme doesn't mention
that and I think it is good to have a first usage example which will just
work after a copy-paste into the repl. This allows to avoid frustration.

вс, 1 янв. 2023 г., 03:11 Alexander Artemenko ***@***.***>:

**Comment by svetlyak40wt** [comment]
> The current readme already has it as just basic.

Yeah, now I see it. I've took original code from [shinmera.github.io/action-list](https://shinmera.github.io/action-list)

How do you update the docs? Probably a github action should be added to build and update docs automatically. For my projects I'm using this action: https://40ants.com/build-docs/ created specially for Common Lisp projects.

**Comment by Shinmera** [comment]
You run staple. An action isn't a good idea as the docs are included on the master branch.

**Pull request closed without merging**
